// Shared inline style helpers for the admin panel — follows the site design system

export const aS = {
  // Typography
  label: {
    fontFamily: 'var(--fm)',
    fontSize: '.5rem',
    letterSpacing: '.15em',
    textTransform: 'uppercase' as const,
    color: 'var(--ink-3)',
    display: 'block',
    marginBottom: '.4rem',
  },
  eyebrow: {
    fontFamily: 'var(--fm)',
    fontSize: '.5rem',
    letterSpacing: '.2em',
    textTransform: 'uppercase' as const,
    color: 'var(--gold)',
  },

  // Form controls
  input: {
    width: '100%',
    padding: '.65rem .9rem',
    background: 'var(--cream-d)',
    border: '1px solid var(--rule)',
    fontFamily: 'var(--fb)',
    fontSize: '.85rem',
    color: 'var(--ink)',
    outline: 'none',
    boxSizing: 'border-box' as const,
  },
  textarea: {
    width: '100%',
    padding: '.65rem .9rem',
    background: 'var(--cream-d)',
    border: '1px solid var(--rule)',
    fontFamily: 'var(--fb)',
    fontSize: '.85rem',
    color: 'var(--ink)',
    outline: 'none',
    resize: 'vertical' as const,
    boxSizing: 'border-box' as const,
  },
  select: {
    width: '100%',
    padding: '.65rem .9rem',
    background: 'var(--cream-d)',
    border: '1px solid var(--rule)',
    fontFamily: 'var(--fb)',
    fontSize: '.85rem',
    color: 'var(--ink)',
    outline: 'none',
    boxSizing: 'border-box' as const,
    cursor: 'pointer',
  },

  // Layout containers
  card: {
    background: 'var(--cream)',
    border: '1px solid var(--rule)',
  },
  sectionBlock: {
    background: 'var(--cream)',
    border: '1px solid var(--rule)',
    marginBottom: '1rem',
  },
  fieldGroup: {
    display: 'grid' as const,
    gap: '1rem',
    marginBottom: '1rem',
  },
  grid2: {
    display: 'grid' as const,
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '1rem',
  },
  grid3: {
    display: 'grid' as const,
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '1rem',
  },

  // Buttons
  btnPrimary: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '.4rem',
    fontFamily: 'var(--fm)',
    fontSize: '.52rem',
    letterSpacing: '.12em',
    textTransform: 'uppercase' as const,
    background: 'var(--navy)',
    color: 'var(--cream)',
    border: 'none',
    padding: '.65rem 1.4rem',
    cursor: 'pointer',
    transition: 'opacity .2s',
  },
  btnSecondary: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '.4rem',
    fontFamily: 'var(--fm)',
    fontSize: '.52rem',
    letterSpacing: '.12em',
    textTransform: 'uppercase' as const,
    background: 'transparent',
    color: 'var(--ink)',
    border: '1px solid var(--rule)',
    padding: '.65rem 1.4rem',
    cursor: 'pointer',
    transition: 'border-color .2s',
  },
  btnDanger: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '.4rem',
    fontFamily: 'var(--fm)',
    fontSize: '.52rem',
    letterSpacing: '.12em',
    textTransform: 'uppercase' as const,
    background: 'transparent',
    color: '#c0392b',
    border: '1px solid rgba(192,57,43,.3)',
    padding: '.65rem 1.4rem',
    cursor: 'pointer',
  },
  btnGhost: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '.4rem',
    fontFamily: 'var(--fm)',
    fontSize: '.5rem',
    letterSpacing: '.1em',
    textTransform: 'uppercase' as const,
    background: 'transparent',
    color: 'var(--ink-3)',
    border: 'none',
    padding: '.4rem .6rem',
    cursor: 'pointer',
  },

  // Toggle
  toggleActive: {
    display: 'inline-flex' as const,
    alignItems: 'center',
    gap: '.35rem',
    fontFamily: 'var(--fm)',
    fontSize: '.48rem',
    letterSpacing: '.12em',
    textTransform: 'uppercase' as const,
    background: 'rgba(143,110,74,.12)',
    color: 'var(--gold)',
    border: '1px solid rgba(143,110,74,.3)',
    padding: '.35rem .8rem',
    cursor: 'pointer',
  },
  toggleInactive: {
    display: 'inline-flex' as const,
    alignItems: 'center',
    gap: '.35rem',
    fontFamily: 'var(--fm)',
    fontSize: '.48rem',
    letterSpacing: '.12em',
    textTransform: 'uppercase' as const,
    background: 'var(--cream-d)',
    color: 'var(--ink-3)',
    border: '1px solid var(--rule)',
    padding: '.35rem .8rem',
    cursor: 'pointer',
  },

  // Table
  th: {
    fontFamily: 'var(--fm)',
    fontSize: '.48rem',
    letterSpacing: '.15em',
    textTransform: 'uppercase' as const,
    color: 'var(--ink-3)',
    padding: '.8rem 1rem',
    textAlign: 'left' as const,
    borderBottom: '1px solid var(--rule)',
    background: 'var(--cream-d)',
  },
  td: {
    padding: '.8rem 1rem',
    borderBottom: '1px solid var(--rule)',
    fontFamily: 'var(--fb)',
    fontSize: '.82rem',
    color: 'var(--ink)',
    verticalAlign: 'middle' as const,
  },
};
