import { doc, setDoc, Firestore } from 'firebase/firestore';

export type PageId = 'home' | 'mentoria' | 'consultoria' | 'prof_paulo' | 'servicos' | 'fale_comigo' | 'area_do_aluno';

// ─── DEFAULT CONTENT ──────────────────────────────────────────────────────────

export const PAGE_DEFAULTS: Record<PageId, Record<string, any>> = {

  // ── HOME ───────────────────────────────────────────────────────────────────
  home: {
    hero: {
      visivel: true,
      headline_linha1: 'Sua equipe vende.',
      headline_linha2: 'Mas poderia vender',
      headline_destaque: 'mais, e melhor.',
      tensao: 'A maioria dos times comerciais trabalha duro — mas sem método, estratégia e gestão real, esforço não vira resultado.',
      subtexto: 'Prof. Paulo H. Donassolo forma gestores e equipes comerciais que transformam processo em performance, consistência em crescimento.',
      cta_primario_texto: 'Quero conversar',
      cta_primario_link: '#/fale-comigo',
      cta_secundario_texto: 'Conheça o Prof. Paulo',
      cta_secundario_link: '#/prof-paulo',
      credencial_1_numero: '25+',
      credencial_1_label: 'anos de mercado',
      credencial_2_numero: '20+',
      credencial_2_label: 'clientes atendidos',
      credencial_3_numero: '3',
      credencial_3_label: 'livros publicados',
      foto_url: '',
      foto_alt: 'Prof. Paulo H. Donassolo',
    },
    metodologia: {
      visivel: true,
      eyebrow: 'A Metodologia',
      intro_texto: 'Um caminho com começo, meio e fim.',
      passo_1_num: '01', passo_1_tag: 'Diagnóstico', passo_1_titulo: 'Diagnóstico',
      passo_1_descricao: 'Mapeamos o estado real da equipe: gaps de processo, comportamento e gestão.',
      passo_2_num: '02', passo_2_tag: 'Estruturação', passo_2_titulo: 'Estruturação',
      passo_2_descricao: 'Definimos o método comercial, papéis claros e indicadores relevantes.',
      passo_3_num: '03', passo_3_tag: 'Ativação', passo_3_titulo: 'Ativação',
      passo_3_descricao: 'Treinamos, acompanhamos e ajustamos em campo — com resultado mensurável.',
      passo_4_num: '04', passo_4_tag: 'Sustentação', passo_4_titulo: 'Sustentação',
      passo_4_descricao: 'A liderança assume o processo. O time vende sem depender de você.',
    },
    autoridade: {
      visivel: true,
      eyebrow: 'Trajetória',
      titulo_linha1: 'Quem está do outro',
      titulo_linha2: 'lado da mesa.',
      titulo_linha3: '',
      narrativa_paragrafo_1: 'Mais de 25 anos como Gerente e Diretor Comercial em empresas de indústria de bens de consumo e distribuição no Brasil. Liderou equipes de 5 a 80 profissionais de vendas.',
      narrativa_paragrafo_2: 'Professor de MBA e pós-graduação em Vendas, Negociação e Gestão Comercial — ESPM, Unisinos e outras instituições. Mais de 20 anos em sala de aula.',
      citacao_texto: '"Método sem gestão é teoria. Gestão sem método é caos."',
      foto_url: '',
      foto_alt: 'Prof. Paulo H. Donassolo',
    },
    situacoes: {
      visivel: true,
      eyebrow: 'Você está aqui?',
      titulo: 'Se alguma dessas situações parece familiar, podemos ajudar.',
      subtitulo: '',
      situacao_1_marker: 'Situação 01',
      situacao_1_titulo: 'Vendedores que dependem de você',
      situacao_1_descricao: 'Toda negociação complexa escala para você. O time não tem autonomia para fechar.',
      situacao_2_marker: 'Situação 02',
      situacao_2_titulo: 'Meta atingida, mas sem consistência',
      situacao_2_descricao: 'Meses bons e meses ruins sem explicação. Não há processo — há sorte.',
      situacao_3_marker: 'Situação 03',
      situacao_3_titulo: 'Turnover alto e onboarding lento',
      situacao_3_descricao: 'Cada saída custa meses de ramp-up. O conhecimento não fica na empresa.',
      situacao_4_marker: 'Situação 04',
      situacao_4_titulo: 'Gestores que gerenciam na intuição',
      situacao_4_descricao: 'Reuniões sem pauta, feedback sem método, pipeline sem visibilidade real.',
    },
    servicos: {
      visivel: true,
      eyebrow: 'Como posso ajudar',
      titulo: 'Escolha o formato certo para o seu momento.',
      subtitulo: '',
      servico_1_titulo: 'Mentoria',
      servico_1_descricao: 'Para gestores e líderes comerciais que querem acelerar resultados com acompanhamento próximo e personalizado.',
      servico_1_link_texto: 'Saiba mais', servico_1_link_url: '#/mentoria',
      servico_2_titulo: 'Consultoria',
      servico_2_descricao: 'Diagnóstico, estruturação e ativação do processo comercial — da estratégia à execução em campo.',
      servico_2_link_texto: 'Saiba mais', servico_2_link_url: '#/consultoria',
      servico_3_titulo: 'Cursos e Formações',
      servico_3_descricao: 'Programas práticos para times comerciais e líderes que querem evoluir com método e consistência.',
      servico_3_link_texto: 'Ver programas', servico_3_link_url: '#/cursos',
      servico_4_titulo: 'Conteúdo',
      servico_4_descricao: 'Artigos, vídeos e recursos para quem quer aprender gestão comercial de forma aplicada e direta.',
      servico_4_link_texto: 'Explorar', servico_4_link_url: '#/conteudo',
      servico_4_tag: 'Gratuito',
    },
    conteudo_recente: {
      visivel: true,
      eyebrow: 'Conteúdo',
      titulo: 'Últimos artigos',
      link_ver_todos_texto: 'Ver todos',
      link_ver_todos_url: '#/conteudo',
    },
    newsletter: {
      visivel: true,
      eyebrow: 'Newsletter',
      titulo_linha1: 'Uma ideia aplicável',
      titulo_destaque: 'por semana.',
      subtexto: 'Reflexões sobre gestão comercial, liderança e desenvolvimento de times — direto para o seu e-mail, sem ruído.',
      botao_texto: 'Quero receber',
      nota_privacidade: 'Sem spam. Cancelamento em um clique.',
    },
    recursos: {
      visivel: true,
      recurso_1_marker: 'Plataforma',
      recurso_1_titulo: 'Área do Aluno',
      recurso_1_descricao: 'Acesse os materiais dos programas e formações com login seguro.',
      recurso_1_link_texto: 'Acessar plataforma', recurso_1_link_url: '#/area-do-aluno',
      recurso_2_marker: 'Udemy · ESPM',
      recurso_2_titulo: 'Cursos Online',
      recurso_2_descricao: 'Formações práticas disponíveis nas principais plataformas de ensino.',
      recurso_2_link_texto: 'Ver cursos', recurso_2_link_url: '#/cursos',
      recurso_3_marker: 'Amazon',
      recurso_3_titulo: 'Livros',
      recurso_3_descricao: 'Três livros publicados sobre gestão de vendas, liderança e performance comercial.',
      recurso_3_link_texto: 'Conhecer os livros', recurso_3_link_url: '#/recursos',
    },
    cta_final: {
      visivel: true,
      eyebrow: 'Próximo passo',
      titulo_linha1: 'Vamos conversar sobre',
      titulo_destaque: 'o seu desafio?',
      subtexto: 'Uma conversa de 30 minutos para entender o que está travando seu time e como podemos resolver juntos.',
      cta_primario_texto: 'Agendar conversa', cta_primario_link: '#/fale-comigo',
      cta_secundario_texto: 'Ver todos os serviços', cta_secundario_link: '#/servicos',
    },
  },

  // ── MENTORIA ──────────────────────────────────────────────────────────────
  mentoria: {
    hero: {
      visivel: true,
      eyebrow: 'Mentoria Comercial',
      subtexto: 'Para empreendedores, empresários e gestores comerciais de PMEs que querem estruturar a área de vendas com método.',
      titulo_linha1: '90 dias. Diagnóstico,',
      titulo_linha2: 'plano e implementação.',
      titulo_destaque: 'plano e implementação.',
      cta_primario_texto: 'Quero conhecer o programa', cta_primario_link: '#/fale-comigo',
      cta_secundario_texto: 'Ver como funciona', cta_secundario_link: '',
      card_label: 'O programa em números',
      card_stat_1_numero: '90', card_stat_1_titulo: 'Dias de programa', card_stat_1_descricao: '',
      card_stat_2_numero: '12', card_stat_2_titulo: 'Sessões individuais', card_stat_2_descricao: '',
      card_stat_3_numero: '04', card_stat_3_titulo: 'Fases estruturadas', card_stat_3_descricao: '',
      card_stat_4_numero: '∞', card_stat_4_titulo: 'Suporte WhatsApp', card_stat_4_descricao: '',
    },
    problema: {
      visivel: true,
      eyebrow: 'O problema',
      titulo: '',
      problema_1: 'A equipe de vendas existe, mas o processo depende de você para funcionar.',
      problema_2: 'Sua empresa está crescendo e você está perdendo o controle da gestão.',
      problema_3: 'As metas são definidas, mas o caminho para atingi-las não está claro para ninguém.',
      problema_4: 'Os vendedores perdem negócios que poderiam ter fechado — e você não sabe onde está o gargalo.',
      problema_5: 'Você gerencia resultado final, não o processo que gera o resultado.',
      citacao_texto: 'O problema raramente é o vendedor. Geralmente está na falta de um processo de gestão, de um método de trabalho e de acompanhamento real das vendas.',
    },
    para_quem: {
      visivel: true,
      eyebrow: 'Para quem é',
      titulo: '',
      para_quem_1: 'Dono, empreendedor ou gestor comercial de uma PME de indústria ou distribuição.',
      para_quem_2: 'Sua equipe de vendas não está atingindo o potencial que você sabe que ela tem.',
      para_quem_3: 'Você precisa entrar nas negociações importantes para elas fecharem.',
      para_quem_4: 'As metas existem, mas o processo para atingi-las não está claro para ninguém.',
      para_quem_5: 'Você quer crescer sem depender só de você para que as vendas aconteçam.',
      nao_para_quem_titulo: 'Não é para quem',
      nao_para_quem_1: 'Quem quer receitas prontas, respostas rápidas ou soluções mágicas.',
      nao_para_quem_2: 'Quem busca palestra ou treinamento pontual sem acompanhamento.',
      nao_para_quem_3: 'Quem não está disposto a executar entre as sessões.',
      nao_para_quem_4: 'Quem não tem tempo para desenvolver a gestão comercial e as pessoas.',
      card_resultado_label: '', card_resultado_titulo: '', card_resultado_subtexto: '',
      card_stat_1_numero: '', card_stat_1_label: '',
      card_stat_2_numero: '', card_stat_2_label: '',
      card_stat_3_numero: '', card_stat_3_label: '',
    },
    como_funciona: {
      visivel: true,
      eyebrow: 'Como funciona',
      titulo: '90 dias. 12 sessões. 4 fases.',
      subtexto: '',
      fase_1_nome: 'Diagnóstico', fase_1_semanas: 'Semanas 1–3',
      fase_1_descricao: 'Mapeamos o processo de vendas e gestão atual, identificamos os gargalos reais e entendemos como a equipe está estruturada e gerida.',
      fase_1_entregavel: 'Relatório de Diagnóstico Comercial',
      fase_2_nome: 'Plano', fase_2_semanas: 'Semanas 4–5',
      fase_2_descricao: 'Definimos as 3 prioridades de trabalho e construímos o plano de ação semana a semana — o que atacar, como e em que ordem.',
      fase_2_entregavel: 'Plano de Ação estruturado',
      fase_3_nome: 'Implementação', fase_3_semanas: 'Semanas 5–10',
      fase_3_descricao: 'Executamos o plano com acompanhamento semanal. Cada sessão tem pauta definida, registro e ações claras para a semana seguinte.',
      fase_3_entregavel: 'Relatório de Execução do Programa',
      fase_4_nome: 'Consolidação', fase_4_semanas: 'Semanas 11–12',
      fase_4_descricao: 'Avaliamos os resultados, documentamos o que ficou funcionando e construímos o plano de continuidade para as próximas 4 semanas sem o mentor.',
      fase_4_entregavel: 'Relatório Final do Programa',
    },
    inclusos: {
      visivel: true,
      eyebrow: 'O que está incluído',
      titulo: '',
      incluso_1: '12 sessões individuais de 60 a 90 minutos — uma por semana.',
      incluso_2: 'Relatório de Diagnóstico Comercial completo.',
      incluso_3: 'Plano de Ação estruturado por semana.',
      incluso_4: 'Templates, ferramentas e frameworks aplicáveis imediatamente.',
      incluso_5: 'Suporte por WhatsApp entre sessões (dias úteis, 9h–18h Lisboa).',
      incluso_6: 'Relatório Final com evolução e próximos passos.',
      resumo_label: '',
      resumo_stat_1_numero: '12', resumo_stat_1_titulo: 'sessões', resumo_stat_1_descricao: '',
      resumo_stat_2_numero: '90', resumo_stat_2_titulo: 'dias', resumo_stat_2_descricao: '',
      resumo_stat_3_numero: '4', resumo_stat_3_titulo: 'fases', resumo_stat_3_descricao: '',
      resumo_stat_4_numero: '∞', resumo_stat_4_titulo: 'suporte', resumo_stat_4_descricao: '',
    },
    mentoria_customizada: {
      visivel: true,
      eyebrow: '',
      titulo: 'Precisa de algo diferente?',
      intro_texto: '',
      card_1_num: '01', card_1_titulo: 'Mentoria Individual Personalizada', card_1_descricao: '', card_1_tags: ['Individual'],
      card_2_num: '02', card_2_titulo: 'Mentoria em Grupo', card_2_descricao: '', card_2_tags: ['Grupos'],
      card_3_num: '03', card_3_titulo: 'Projeto Corporativo', card_3_descricao: '', card_3_tags: ['In-company'],
      cta_texto_frase: '', cta_botao_texto: 'Fale comigo', cta_botao_link: '#/fale-comigo',
    },
    sobre_mentor: {
      visivel: true,
      eyebrow: 'Quem conduz',
      titulo_linha1: 'Prof. Paulo H. Donassolo',
      titulo_destaque: '',
      citacao_texto: '',
      card_nome: 'Prof. Paulo H. Donassolo',
      card_subtitulo: 'Professor · Consultor · Mentor Comercial',
      card_item_1: 'Mais de 25 anos como Gerente e Diretor Comercial em indústrias de bens de consumo e distribuição.',
      card_item_2: 'Mais de 20 anos como professor de MBA e pós-graduação — ESPM e Unisinos.',
      card_item_3: 'Autor de livros sobre gestão comercial, vendas e negociação.',
      card_item_4: 'Mestre em Administração de Empresas, MBA em Marketing Estratégico e MBA em Gestão por Processos.',
      card_item_5: 'Formador certificado pelo IEFP (Portugal).',
    },
    faq: {
      visivel: true,
      faq: [
        { pergunta: 'As sessões são presenciais ou online?', resposta: 'Online, via Google Meet, Zoom ou Teams. Isso permite flexibilidade de horário e atendimento independente de localização.', ordem: 1 },
        { pergunta: 'O que acontece se eu precisar remarcar uma sessão?', resposta: 'Sem problema. Avise com pelo menos 24 horas de antecedência e remarcamos sem custo.', ordem: 2 },
        { pergunta: 'Como funciona o suporte por WhatsApp?', resposta: 'Disponível de segunda a sexta, das 9h às 18h (horário de Lisboa). Para dúvidas rápidas sobre o que foi discutido na sessão.', ordem: 3 },
        { pergunta: 'Em quanto tempo vejo resultados?', resposta: 'As primeiras mudanças de processo começam na Fase 2 — semana 5. O programa é de implementação, não de teoria.', ordem: 4 },
        { pergunta: 'Posso continuar após os 90 dias?', resposta: 'Sim. Na Sessão 12 apresentamos as opções de continuidade — nova rodada de mentoria, consultoria direta ou acesso aos cursos online.', ordem: 5 },
      ],
    },
    cta_final: {
      visivel: true,
      eyebrow: 'Próximo passo',
      titulo_linha1: 'Comece com uma sessão de',
      titulo_destaque: 'diagnóstico gratuita.',
      subtexto: '30 minutos. Olhamos juntos onde sua área comercial está travando e o que faz mais sentido atacar primeiro. Sem compromisso.',
      nota: 'Sem compromisso. Sem custo.',
      cta_primario_texto: 'Agendar diagnóstico gratuito', cta_primario_link: '#/fale-comigo',
      cta_secundario_texto: '', cta_secundario_link: '',
    },
  },

  // ── CONSULTORIA ──────────────────────────────────────────────────────────
  consultoria: {
    hero: {
      visivel: true,
      eyebrow: 'Consultoria',
      subtexto: 'Estruturamos e ativamos o processo comercial da sua empresa — da estratégia à implementação em campo.',
      titulo_linha1: 'Do diagnóstico à execução.',
      titulo_linha2: '',
      titulo_destaque: 'Com resultado mensurável.',
      cta_primario_texto: 'Solicitar diagnóstico gratuito', cta_primario_link: '#/fale-comigo',
      cta_secundario_texto: 'Ver também: Mentoria', cta_secundario_link: '#/mentoria',
    },
    problema: {
      visivel: true,
      eyebrow: 'O problema',
      titulo: '',
      problema_1: 'A equipe vende, mas sem processo definido — cada vendedor trabalha do seu jeito.',
      problema_2: 'Gestores acompanham resultado final, não o processo que gera resultado.',
      problema_3: 'Novos vendedores demoram meses para atingir produtividade.',
      problema_4: 'Os indicadores medidos não ajudam a tomar decisões de gestão.',
      problema_5: 'A liderança comercial não tem rituais de gestão estruturados.',
      citacao_texto: 'A maioria dos problemas comerciais não é de vendedor — é de processo, gestão e método.',
    },
    frentes: {
      visivel: true,
      eyebrow: 'Áreas de atuação',
      titulo: 'O que podemos trabalhar juntos.',
      card_1_titulo: 'Diagnóstico Comercial',
      card_1_descricao: 'Avaliação profunda do processo de vendas, da equipe, da gestão e dos indicadores para identificar os gargalos reais.',
      card_2_titulo: 'Estruturação de Processos',
      card_2_descricao: 'Desenho ou redesenho do funil de vendas, etapas, critérios de avanço, responsabilidades e cadência de atividades.',
      card_3_titulo: 'Treinamento de Equipes',
      card_3_descricao: 'Programas customizados de capacitação para vendedores e líderes comerciais — técnica de vendas, gestão e negociação.',
      card_4_titulo: 'Gestão e Liderança Comercial',
      card_4_descricao: 'Implantação de rotinas de gestão: reuniões de pipeline, 1:1, relatórios de campo e rituais de acompanhamento.',
      card_5_titulo: 'Indicadores e Dashboards',
      card_5_descricao: 'Definição dos KPIs corretos para cada etapa do funil e construção dos painéis de acompanhamento da gestão.',
      card_6_titulo: 'Onboarding e Ramp-up',
      card_6_descricao: 'Estruturação do processo de entrada de novos vendedores para reduzir o tempo até a primeira venda.',
    },
    metodo: {
      visivel: true,
      eyebrow: 'Metodologia',
      titulo: 'Um processo com começo, meio e fim.',
      etapa_1_nome: 'Diagnóstico', etapa_1_tag: '', etapa_1_entregavel: 'Relatório de Diagnóstico Comercial',
      etapa_1_descricao: 'Mapeamento completo do processo comercial: estrutura da equipe, indicadores, pipeline, gestão e cultura de vendas.',
      etapa_2_nome: 'Estruturação', etapa_2_tag: '', etapa_2_entregavel: 'Manual do Processo Comercial',
      etapa_2_descricao: 'Definição do processo comercial ideal, papéis e responsabilidades, metas e indicadores, e plano de implementação.',
      etapa_3_nome: 'Ativação', etapa_3_tag: '', etapa_3_entregavel: 'Relatório de Execução',
      etapa_3_descricao: 'Treinamento da equipe, acompanhamento em campo, ajustes e implantação das ferramentas de gestão.',
      etapa_4_nome: 'Sustentação', etapa_4_tag: '', etapa_4_entregavel: 'Plano de Continuidade',
      etapa_4_descricao: 'Transferência de responsabilidade para a liderança interna. O time opera com o novo processo de forma autônoma.',
      etapa_5_nome: '', etapa_5_tag: '', etapa_5_entregavel: '', etapa_5_descricao: '',
    },
    para_quem: {
      visivel: true,
      eyebrow: 'Para quem',
      titulo: '',
      para_quem_1: 'Empresas de indústria, distribuição ou serviços B2B com equipe comercial.',
      para_quem_2: 'Times de 3 a 80 vendedores que precisam de método e processo.',
      para_quem_3: 'Gestores que querem implementar rituais de acompanhamento reais.',
      para_quem_4: 'Empresas que cresceram e o modelo informal já não funciona.',
      para_quem_5: 'Líderes que querem uma visão externa e estruturada da sua área comercial.',
      card_setores_label: 'Setores atendidos',
      card_setores_tags: ['Indústria', 'Distribuição', 'Serviços B2B', 'Varejo', 'Agronegócio'],
    },
    diferencial: {
      visivel: true,
      eyebrow: 'Por que escolher',
      titulo: 'Quem ensina também já executou.',
      ponto_1_titulo: 'Experiência de mercado real',
      ponto_1_descricao: 'Mais de 25 anos gerindo equipes comerciais em indústria e distribuição — não é consultoria teórica.',
      ponto_2_titulo: 'Método testado em sala de aula',
      ponto_2_descricao: 'Mais de 20 anos como professor de MBA. O que funciona na prática também é ensinado com rigor.',
      ponto_3_titulo: 'Foco em PME',
      ponto_3_descricao: 'Especialização em empresas de médio porte onde o gestor acumula papéis e o processo precisa ser prático.',
      ponto_4_titulo: 'Resultado mensurável',
      ponto_4_descricao: 'Cada projeto começa com diagnóstico claro e termina com indicadores que mostram o que mudou.',
      citacao_texto: '"O que não é medido não é gerido. O que não é gerido não melhora."',
    },
    faq: {
      visivel: true,
      faq: [
        { pergunta: 'Qual é a duração mínima de um projeto de consultoria?', resposta: 'Depende do escopo. Um diagnóstico isolado pode ser concluído em 3 a 4 semanas. Um projeto completo costuma durar de 3 a 6 meses.', ordem: 1 },
        { pergunta: 'A consultoria é presencial ou remota?', resposta: 'Ambas. Os diagnósticos e treinamentos podem ser feitos remotamente ou presencialmente dependendo da localização e necessidade do cliente.', ordem: 2 },
        { pergunta: 'Vocês trabalham com quais setores?', resposta: 'Especialização em indústria de bens de consumo, distribuição e serviços B2B. Empresas com equipes comerciais de 3 a 80 pessoas.', ordem: 3 },
        { pergunta: 'Como é definido o valor do projeto?', resposta: 'O valor é definido após o diagnóstico inicial — que é gratuito. O investimento depende do escopo, do tamanho da equipe e da complexidade do projeto.', ordem: 4 },
      ],
    },
    cta_final: {
      visivel: true,
      eyebrow: 'Próximo passo',
      titulo_linha1: 'Vamos olhar para o seu',
      titulo_destaque: 'processo comercial?',
      subtexto: 'Começamos com um diagnóstico gratuito de 30 minutos para entender onde está o gargalo e o que faz mais sentido atacar.',
      cta_primario_texto: 'Solicitar diagnóstico gratuito', cta_primario_link: '#/fale-comigo',
      cta_secundario_texto: '', cta_secundario_link: '',
    },
  },

  // ── PROF. PAULO ──────────────────────────────────────────────────────────
  prof_paulo: {
    hero: {
      visivel: true,
      eyebrow: 'Prof. Paulo H. Donassolo',
      titulo_linha1: '25 anos no campo.',
      titulo_linha2: '20 anos na sala de aula.',
      titulo_linha3: 'Ainda aprendendo.',
      citacao_texto: '"Método sem gestão é teoria. Gestão sem método é caos."',
      credencial_1_numero: '25+', credencial_1_label: 'anos de mercado',
      credencial_2_numero: '20+', credencial_2_label: 'anos em MBA',
      credencial_3_numero: '3', credencial_3_label: 'livros publicados',
      foto_url: '', foto_alt: 'Prof. Paulo H. Donassolo',
    },
    narrativa: {
      visivel: true,
      eyebrow: 'A Jornada',
      titulo: 'Do campo para a sala de aula.',
      paragrafo_1: 'Mais de 14 anos como Gerente e Diretor Comercial em empresas de indústria de bens de consumo e distribuição no Brasil. Liderou equipes de 5 a 80 profissionais de vendas.',
      paragrafo_2: 'Professor de MBA e pós-graduação em Vendas, Negociação e Gestão Comercial — ESPM, Unisinos e outras instituições. Mais de 20 anos em sala de aula.',
      paragrafo_3: 'Fundação da consultoria própria. Atende PMEs de indústria, distribuição e serviços B2B no Brasil e em Portugal com foco em estruturação comercial.',
      paragrafo_4: 'Atuação em Portugal e no Brasil como consultor, mentor e formador comercial certificado pelo IEFP.',
      pullquote_texto: '"A melhor gestão é aquela que o time não precisa que você explique duas vezes."',
      pullquote_citacao: 'Prof. Paulo H. Donassolo',
    },
    timeline: {
      visivel: true,
      eyebrow: 'Linha do Tempo',
      titulo: 'Uma carreira construída nas duas pontas.',
    },
    filosofia: {
      visivel: true,
      eyebrow: 'Filosofia & Formação',
      titulo: 'Academicamente fundamentado.',
      pilar_1_numero: '01', pilar_1_titulo: 'Prática → Conceito → Prática', pilar_1_descricao: 'O conhecimento que não volta para o campo não tem valor. Tudo o que ensino passei primeiro pelo filtro da execução real.',
      pilar_2_numero: '02', pilar_2_titulo: 'Processo antes de talento', pilar_2_descricao: 'Times consistentes são construídos com processo, não dependem de talentos individuais.',
      pilar_3_numero: '03', pilar_3_titulo: 'Gestão com evidência', pilar_3_descricao: 'Decisões de gestão precisam ser baseadas em dados, não em impressões ou intuição.',
      pilar_4_numero: '04', pilar_4_titulo: 'Aprendizado contínuo', pilar_4_descricao: 'Quem para de aprender para de crescer. Continuo em sala de aula como aluno tanto quanto como professor.',
      citacao_texto: '"O gestor que não aprende, não tem o que ensinar para o seu time."',
      formacao_label: 'Formação acadêmica',
      formacao_item_1_badge: 'MSc', formacao_item_1_titulo: 'Mestre em Administração de Empresas', formacao_item_1_descricao: 'Unisinos',
      formacao_item_2_badge: 'MBA', formacao_item_2_titulo: 'MBA em Marketing Estratégico', formacao_item_2_descricao: 'FGV',
      formacao_item_3_badge: 'MBA', formacao_item_3_titulo: 'MBA em Gestão por Processos', formacao_item_3_descricao: 'FGV',
      formacao_item_4_badge: 'IEFP', formacao_item_4_titulo: 'Formador Certificado', formacao_item_4_descricao: 'IEFP — Portugal',
      formacao_item_5_badge: 'IA', formacao_item_5_titulo: 'Inteligência Artificial aplicada', formacao_item_5_descricao: 'Formação continuada',
    },
    onde_leciona: {
      visivel: true,
      eyebrow: 'Onde leciona',
      titulo: 'Em sala de aula há mais de 20 anos.',
      subtexto: '',
      inst_1_tipo: 'MBA e Pós-graduação', inst_1_nome: 'ESPM', inst_1_descricao: 'Vendas, Negociação e Gestão Comercial',
      inst_2_tipo: 'Pós-graduação', inst_2_nome: 'Unisinos', inst_2_descricao: 'Gestão Comercial e Liderança de Times',
      inst_3_tipo: 'Corporativo', inst_3_nome: 'In-company', inst_3_descricao: 'Formações customizadas para empresas',
    },
    livros: {
      visivel: true,
      eyebrow: 'Publicações',
      titulo: 'Conhecimento que fica.',
      subtexto: '',
      livro_1_numero: '01', livro_1_titulo: 'Gestão de Equipes Comerciais',
      livro_1_descricao: 'Como liderar, motivar e desenvolver times de alta performance em vendas',
      livro_1_link_amazon: '', livro_1_capa_url: '',
      livro_2_numero: '02', livro_2_titulo: 'Vendas B2B: Processo e Método',
      livro_2_descricao: 'Um guia prático para estruturar o processo de vendas em empresas de indústria e distribuição',
      livro_2_link_amazon: '', livro_2_capa_url: '',
      livro_3_numero: '03', livro_3_titulo: 'A Arte da Negociação Comercial',
      livro_3_descricao: 'Técnicas e estratégias para negociadores de alta performance',
      livro_3_link_amazon: '', livro_3_capa_url: '',
    },
    cta_final: {
      visivel: true,
      eyebrow: 'Trabalhe comigo',
      titulo: 'Vamos conversar sobre o seu desafio?',
      subtexto: 'Mentoria individual, consultoria para equipes ou formação corporativa. Encontramos o formato certo para o seu momento.',
      cta_primario_texto: 'Fale comigo', cta_primario_link: '#/fale-comigo',
      cta_secundario_texto: 'Ver serviços', cta_secundario_link: '#/servicos',
    },
  },

  // ── SERVIÇOS ─────────────────────────────────────────────────────────────
  servicos: {
    hero: {
      visivel: true,
      eyebrow: 'Serviços',
      subtexto: 'Mentoria individual, consultoria para empresas, formações para times ou conteúdo gratuito. O ponto de entrada é diferente — o destino é o mesmo: um processo comercial que funciona sem depender de você.',
      titulo_linha1: 'Escolha o formato certo',
      titulo_linha2: '',
      titulo_destaque: 'para o seu momento.',
    },
    intro: {
      visivel: true,
      eyebrow: '',
      titulo: '',
      card_como_escolher_label: 'Como escolher',
      intro_texto: '',
      opcao_1_titulo: 'Gestor ou líder que quer acelerar resultado individual', opcao_1_descricao: 'Mentoria Comercial — 90 dias',
      opcao_2_titulo: 'Empresa que quer estruturar o processo comercial', opcao_2_descricao: 'Consultoria',
      opcao_3_titulo: 'Time que precisa de capacitação com método', opcao_3_descricao: 'Cursos e Formações',
      opcao_4_titulo: 'Quem quer aprender gratuitamente', opcao_4_descricao: 'Conteúdo',
    },
    cards_servicos: {
      visivel: true,
      servico_1_numero: '01', servico_1_tipo_label: 'Individual · 90 dias', servico_1_titulo: 'Mentoria Comercial',
      servico_1_descricao: 'Para gestores e líderes que querem estruturar a área de vendas com método e acompanhamento próximo. 12 sessões, diagnóstico, plano e implementação.',
      servico_1_link_texto: 'Conhecer a Mentoria', servico_1_link_url: '#/mentoria',
      servico_1_tags: ['12 sessões individuais', 'Diagnóstico comercial', 'Plano de ação', 'Suporte WhatsApp'],
      servico_2_numero: '02', servico_2_tipo_label: 'Empresas · PME', servico_2_titulo: 'Consultoria',
      servico_2_descricao: 'Diagnóstico, estruturação e ativação do processo comercial — da estratégia à execução em campo.',
      servico_2_link_texto: 'Conhecer a Consultoria', servico_2_link_url: '#/consultoria',
      servico_2_tags: ['Diagnóstico comercial', 'Estruturação de funil', 'Treinamento da equipe', 'Rituais de gestão'],
      servico_3_numero: '03', servico_3_tipo_label: 'Times e Líderes', servico_3_titulo: 'Cursos e Formações',
      servico_3_descricao: 'Programas práticos para equipes comerciais e líderes que querem evoluir com método.',
      servico_3_link_texto: 'Ver Cursos', servico_3_link_url: '#/cursos',
      servico_3_tags: ['Cursos online', 'Formações in company', 'Turmas abertas', 'Certificação'],
      servico_4_numero: '04', servico_4_tipo_label: 'Gratuito', servico_4_titulo: 'Conteúdo',
      servico_4_descricao: 'Artigos, reflexões e ferramentas para quem quer aprender gestão comercial de forma aplicada.',
      servico_4_link_texto: 'Explorar Conteúdo', servico_4_link_url: '#/conteudo',
      servico_4_tags: ['Artigos semanais', 'Newsletter exclusiva', 'Ferramentas e templates', 'Acesso gratuito'],
    },
    comparativo: {
      visivel: true,
      eyebrow: '',
      titulo: '',
      col_1_titulo: 'Mentoria', col_1_itens: ['Individual', '90 dias', '12 sessões', 'Diagnóstico + Plano'],
      col_2_titulo: 'Consultoria', col_2_itens: ['Para empresas', '3–6 meses', 'Equipe completa', 'Diagnóstico + Implementação'],
      col_3_titulo: 'Cursos', col_3_itens: ['Times e líderes', 'Flexível', 'Online ou in company', 'Certificação'],
      col_4_titulo: 'Conteúdo', col_4_itens: ['Todos', 'Contínuo', 'Online', 'Gratuito'],
    },
    cta_final: {
      visivel: true,
      eyebrow: 'Não sabe qual formato escolher?',
      titulo: 'Conversamos e encontramos juntos o melhor caminho.',
      subtexto: 'Uma conversa de 30 minutos é suficiente para entender o seu momento e recomendar o formato mais adequado.',
      cta_primario_texto: 'Agendar conversa gratuita', cta_primario_link: '#/fale-comigo',
      cta_secundario_texto: '', cta_secundario_link: '',
    },
  },

  // ── FALE COMIGO ──────────────────────────────────────────────────────────
  fale_comigo: {
    hero: {
      visivel: true,
      eyebrow: 'Fale Comigo',
      subtexto: 'Preencha o formulário abaixo e retornarei em até 24 horas úteis.',
      titulo_linha1: 'Vamos conversar sobre',
      titulo_destaque: 'o seu desafio.',
    },
    formulario: {
      visivel: true,
      mensagem_sucesso: 'Mensagem enviada com sucesso! Retornarei em até 24 horas úteis.',
      opcoes_assunto: ['Mentoria Comercial', 'Consultoria', 'Cursos e Formações', 'Palestra / Aula', 'Parceria', 'Outro'],
    },
    contatos: {
      visivel: true,
      numero_whatsapp: '351910298213',
      horario_atendimento: 'Seg–Sex, 9h–18h (Lisboa)',
      email_contato: 'paulo@phdonassolo.com',
      cidade: 'Lisboa, Portugal',
      descricao_atendimento: 'Atendimento presencial e remoto',
    },
    o_que_esperar: {
      visivel: true,
      eyebrow: 'O que esperar',
      titulo: 'Como funciona o contato',
      etapa_1_titulo: 'Recebo sua mensagem', etapa_1_descricao: 'Em até 24h em dias úteis.',
      etapa_2_titulo: 'Avalio o contexto', etapa_2_descricao: 'Leio com atenção antes de responder.',
      etapa_3_titulo: 'Respondo com clareza', etapa_3_descricao: 'Indico o próximo passo mais adequado.',
      etapa_4_titulo: 'Agendamos se fizer sentido', etapa_4_descricao: 'Uma conversa de 30 min sem compromisso.',
    },
    faq: {
      visivel: true,
      faq: [
        { pergunta: 'Em quanto tempo você responde?', resposta: 'Em até 24 horas úteis por e-mail. Para urgências, o WhatsApp é mais rápido.', ordem: 1 },
        { pergunta: 'A primeira conversa é gratuita?', resposta: 'Sim. A conversa de diagnóstico inicial é sempre gratuita e sem compromisso.', ordem: 2 },
        { pergunta: 'Atende empresas fora do Brasil?', resposta: 'Sim. Atendo empresas no Brasil e em Portugal. As sessões são online.', ordem: 3 },
      ],
    },
  },

  // ── ÁREA DO ALUNO ────────────────────────────────────────────────────────
  area_do_aluno: {
    conteudo: {
      visivel: true,
      eyebrow: 'Área do Aluno',
      titulo: 'Em breve. Muito em breve.',
      subtitulo: 'A plataforma de ensino do Prof. Paulo H. Donassolo estará disponível em breve.',
      paragrafo: 'Cursos, formações e materiais exclusivos — tudo em um só lugar, com acesso fácil e seguro.',
      botao_texto: 'Quero ser avisado',
      nota_privacidade: 'Seus dados estão seguros. Nunca enviamos spam.',
      mensagem_confirmacao: 'Cadastro realizado! Você será avisado assim que a plataforma estiver disponível.',
    },
  },
};

// ─── SEED FUNCTIONS ───────────────────────────────────────────────────────────

export async function seedPage(
  db: Firestore,
  pageId: PageId,
  opts: { overwrite?: boolean } = {}
): Promise<void> {
  const data = PAGE_DEFAULTS[pageId];
  if (!data) return;

  for (const [section, sectionData] of Object.entries(data)) {
    await setDoc(
      doc(db, 'site_content', pageId),
      { [section]: sectionData },
      opts.overwrite ? undefined : { merge: true }
    );
  }
}

export async function seedAll(
  db: Firestore,
  opts: { overwrite?: boolean } = {}
): Promise<void> {
  const pages = Object.keys(PAGE_DEFAULTS) as PageId[];
  for (const pageId of pages) {
    await seedPage(db, pageId, opts);
  }
}
